# Generated by Django 4.2 on 2023-04-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('state_or_district', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number_one', models.CharField(max_length=20)),
                ('phone_number_two', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
